name: sync2gitee

on:
  push:
    branches:
      - master
      - dev
      - main
  workflow_dispatch:

jobs:
  repo-sync:
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
      dst_token: ${{ secrets.GITEE_TOKEN }}
      gitee_user: ${{ secrets.GITEE_USER }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: sync github -> gitee
        uses: Yikun/hub-mirror-action@master
        if: env.dst_key && env.dst_token && env.gitee_user
        with:
          src: 'github/${{ github.repository_owner }}'
          dst: 'gitee/xhzwrs'
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: user
          static_list: ${{ github.event.repository.name }}
